### ISSUE TITLE
satetest/ng + Invalid URL

### ISSUE THREAD

**Issue by MartinFerret** [kolodny/safetest#13]
1. In my file.safetest.ts, we have this import :

import { makeSafetestBed } from 'safetest/ng';

Throws this error : TS2307: Cannot find module safetest/ng or its corresponding type declarations

Where does this module come from and how to fix this issue ?

2. Also, after running the command `npm run safetest`, I get :

![image](https://github.com/kolodny/safetest/assets/90469240/f504c41c-7cae-40b6-a260-b1dc0f631918)
I'm running it on localhost obviously, Angular 17.
My script :     

` "safetest": "cross-env OPT_URL=${OPT_URL:-http://localhost:4200}  jest --runInBand --bail=5 --testMatch '**/*.safetest.ts' --setupFilesAfterEnv ./setup-safetest.js --testTimeout=30000"`

**Comment by kolodny** [comment]
I just pushed a change to the fix-windows branch. Can you try again. I was able to get this to work on my windows machine using the vanilla command prompt. You'll need to

- `npm install --legacy-peer-deps` in root of project
- `npm install` in examples/angular-app
- Run `npm start` in one command prompt terminal, keep this terminal running
- Run `npx jest` in another command prompt terminal

**Comment by kolodny** [comment]
Oh looking at over the issue again, on windows you need to change


```bash
OPT_URL=${OPT_URL:-http://localhost:4200}
```

to


```bash
OPT_URL=http://localhost:4200
```

The `${OPT_URL:-http://localhost:4200}` only works on nix based systems

**Comment by MartinFerret** [comment]
Thanks a lot for the explanations, it works regarding the target URL like a charm, setting the url in the steup file is perfect.

Nonetheless, I still have the issue where I can't import the right lib, which is strange cause as you mentionned below, we see that is available, here is what I have when I want to import :

![image](https://github.com/kolodny/safetest/assets/90469240/2ffe7f79-a9e7-4ea3-b609-cf5aafa97c1a)

By choosing safetest/lib/ng, by running my tests it gives the following error :

![image](https://github.com/kolodny/safetest/assets/90469240/898def58-4ed3-4dab-be21-813404953830)

**Comment by kolodny** [comment]
Hmm, this is an issue with your tooling not following the exports field, that's why there's all these top level files like /react.js just to point to the lib one. I'll need to push a release with an ng file as well. For now you should be able to `// @ts-ignore` it

**Comment by kolodny** [comment]
I just [published 0.1.12 release](https://github.com/kolodny/safetest/releases/tag/0.1.12) which has this file, can you give that a try?

**Comment by MartinFerret** [comment]
That's solved it, thanks a lot for your help and guiding @kolodny
