### ISSUE TITLE
OPT_URL

### ISSUE THREAD

**Issue by MartinFerret** [kolodny/safetest#8]
Well, when running tests in examples/angular-app by `npm run safetest`, I get an error regarding the OPT_URL : 

**OPT_URL' is not recognised as an internal or external command
or external command, an executable program or a command file.**

What is this OPT_URL and how to use it ? Is it possible to upgrade the documentation and give us some tips ?

**Comment by kolodny** [comment]
This should be [fixed with how SafeTest now uses cross-env](https://github.com/kolodny/safetest/commit/4fed216a51ccd036cd13c7521a8f64c9a3466c38#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R40). Can you pull the main branch and try again?

**Comment by MartinFerret** [comment]
I've just pulled @kolodny  but I still get that same issue. Is someone else experiencing this ?

**Comment by kolodny** [comment]
What environment are you on?

**Comment by kolodny** [comment]
Also what commands are you running?

**Comment by MartinFerret** [comment]
I'm on windows 11. The error occurs when I run npm run safetest

**Comment by kolodny** [comment]
Are you using command prompt, powershell, or a git-for-windows like shell?

**Comment by MartinFerret** [comment]
I'm using git bash UI for Windows, exactly.

**Comment by kolodny** [comment]
Can you try with branch [fix-windows](https://github.com/kolodny/safetest/tree/fix-windows), you may need to change the [`OPT_URL` part of the script](https://github.com/kolodny/safetest/blob/fix-windows/examples/angular-app/package.json#L9C18-L9C87) with just

```bash
cross-env OPT_URL=http://localhost:4200/angular-app jest ...
```

Due to https://github.com/kentcdodds/cross-env/issues/140

**Comment by kolodny** [comment]
You need to run npm install from the root of the repo

**Comment by MartinFerret** [comment]
I did before running the script

**Comment by kolodny** [comment]
So you should be able to remove and env from package.json and just hardcode everything in the `setup-safetest` file

**Comment by MartinFerret** [comment]
Can you give me an exemple of the script i should be using ?
